### PR TITLE
Show the Temprature and Frequency in their SI units.

### PR DESCRIPTION
**Pull request by jagmeethanspal**
The small change shows the Freq with MHz and Temp with Deg C, whenever the script throttles or un-throttles the CPU.

### CODE REVIEW

**Comment by sanderjo** [comment]
Ah, cool (pun intended) ... that's exactly what I wrote into my temp_throttle.sh ... before seeing this PR. 

So I'm pro accepting this PR.

Snippet from my output

```
unthrottle  69 Celsius. Frequency:  2266  Mhz
unthrottle  69 Celsius. Frequency:  2399  Mhz
throttle    82 Celsius. Frequency:  2266  Mhz
throttle    79 Celsius. Frequency:  2133  Mhz
unthrottle  68 Celsius. Frequency:  2266  Mhz
unthrottle  67 Celsius. Frequency:  2399  Mhz
throttle    80 Celsius. Frequency:  2266  Mhz
unthrottle  70 Celsius. Frequency:  2399  Mhz
throttle    82 Celsius. Frequency:  2266  Mhz
throttle    76 Celsius. Frequency:  2133  Mhz
throttle    77 Celsius. Frequency:  1999  Mhz
throttle    77 Celsius. Frequency:  1866  Mhz
throttle    79 Celsius. Frequency:  1733  Mhz
throttle    79 Celsius. Frequency:  1599  Mhz
throttle    77 Celsius. Frequency:  1466  Mhz
throttle    77 Celsius. Frequency:  1333  Mhz
throttle    77 Celsius. Frequency:  1199  Mhz
unthrottle  69 Celsius. Frequency:  1333  Mhz
unthrottle  70 Celsius. Frequency:  1466  Mhz
```

**Comment by Sepero** [comment]
@jagmeethanspal 
This is the reason I wrote it in shell script from the beginning. When done correctly, super easy to read, editable, and great contributions. Thank you for your submission.

**Comment by jagmeethanspal** [comment]
I am not sure what to do next here, as I am little unsure of the work-flow further.

**Comment by Sepero** [comment]
@jagmeethanspal 
Excellent work. Your contribution will be included in time, but unfortunately I don't have time to dedicate to this project anymore. It would be great if someone else could maintain updates on it. For now, I'm just busy with other things in life. Thank you

**Comment by jagmeethanspal** [comment]
closing

**Pull request closed without merging**
