### PR TITLE
Add Option: sleep interval

### PR DESCRIPTION
**Pull request by stossenbrink**
Thanks for the project.
I was short on thermal paste and found this feature helpful.

### CODE REVIEW

**Comment by Sepero** [comment]
Out of curiosity, how frequently did you require the script to check temperature? 😊

**Comment by Jeremy7701** [comment]
I can't use this great throttling product on my current PC due to lack of temperature sensors; on my old computer I used a modified main loop.
Obviously there are lots of customisation you could do... 

####### Main loop
while true; do
	get_temp # Gets the current temperature and set it to the variable TEMP.
	if   [ $TEMP -gt $MAX_TEMP ]; then # Throttle if too hot.
		throttle
	    **sleep 3**   ###### wait a bit extra
	elif [ $TEMP -le $LOW_TEMP ]; then # Unthrottle if cool.
		unthrottle
	fi
	**sleep 5** ###### The amount of time between checking temperatures.
done

**Comment by stossenbrink** [comment]
> Out of curiosity, how frequently did you require the script to check temperature? blush

While feeding pdfs into [paperless-ng](https://github.com/jonaswinkler/paperless-ng), the temperature was rising at 2C° every second, so I set the target temperature to 65C° and the interval to 0.5s. The temperature peaked at 90C° until the throttling to 0.8Ghz cooled it down. Then a loop began that was wandering around 1.5-2Ghz with 60-70C°.

**Review by jagmeethanspal — APPROVED** [review]

**Comment by Sepero** [comment]
I've implemented this, but in a totally different way and with many more options. Coming in a new release soon. Thank you ❤️

**Pull request closed without merging**
